# prod.yml

name: prod

on:
  release:
    types: [created]

jobs:
  publish:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: 24.x
          registry-url: https://npm.pkg.github.com/
      - run: |
          npm ci
          npm run check
          npm run build --if-present
          npm run test
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
